version: '3'

services:

  db_dev:
    image: mysql:5.7.21
    #        volumes:
    #          - "./volumes/mysql_dev:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_dev
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword